name: '#MoreThanAMom'
favicon: null
layout_spectrum: 0.06988851842470467
typography_spectrum: 0.21634571999311447
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6134124260861427
  lightness: 0.7213854398578405
  saturation: 0.5511937898118049
  rhythmicContrast: 0.21252469578757882
purpose: []
